import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "1024"
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Rest of your layout code remains the same

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
   <html lang="en">
     <body className="min-h-screen bg-slate-900 text-slate-50">
       {children}
     </body>
   </html>
 );
}