export const ALL_SETTERS: { name: string; primaryGyms: string[]; email: string }[] = [
    { name: "Evan", primaryGyms: ["denton", "design"], email: "Evan.Woods@movementgyms.com" },
    { name: "Canon", primaryGyms: ["hill", "plano"], email: "canon.huse@movementgyms.com" },
    { name: "Austin", primaryGyms: ["fortWorth", "grapevine"], email: "Austin.Sivoravong@MovementGyms.com" },
    { name: "Luke S.", primaryGyms: ["design"], email: "Luke.Sherlock@movementgyms.com" },
    { name: "Nicole", primaryGyms: ["grapevine"], email: "Nicole.Baviera@movementgyms.com" },
    { name: "Jack S.", primaryGyms: ["hill", "plano"], email: "Jack.Simon@movementgyms.com" },
    { name: "Kyle", primaryGyms: ["design"], email: "Kyle.baldwin@movementgyms.com" },
    { name: "Fredrik", primaryGyms: ["design"], email: "Fredrik.Baliwis@movementgyms.com" },
    { name: "Brandon", primaryGyms: ["hill", "plano"], email: "Brandon.Mai@MovementGyms.com" },
     { name: "Theo", primaryGyms: ["hill", "plano", "carrolltonTC", "planoTC"], email: "Theo.Massenat@movementgyms.com" },
    { name: "Joe", primaryGyms: ["hill", "plano"], email: "Joseph.Kutsch@movementgyms.com" },
    { name: "Samantha", primaryGyms: ["design", "hill"], email: "Samantha.johnson@movementgyms.com" },
    { name: "Adam K.", primaryGyms: ["denton", "grapevine"], email: "Adam.Knight@MovementGyms.com" },
    { name: "Luigi", primaryGyms: ["denton", "grapevine"], email: "Luigi.Roque@movementgyms.com" },
    { name: "Mikey", primaryGyms: ["denton", "plano"], email: "Mikey.Bennett@movementgyms.com" },
     { name: "Willard", primaryGyms: ["fortWorth", "grapevine"], email: "Willard.Russell@movementgyms.com" },
     { name: "Jack V.", primaryGyms: ["fortWorth", "grapevine"], email: "Jack.Voltz@movementgyms.com" },
     { name: "Henry", primaryGyms: ["carrolltonTC", "planoTC"], email: "Henry.Davis@movementgyms.com" },
     { name: "Matt", primaryGyms: ["carrolltonTC", "planoTC"], email: "Matt.Dendy@movementgyms.com" },
     { name: "Ellis", primaryGyms: ["carrolltonTC", "planoTC"], email: "Ellis.Ernsberger@MovementGyms.com" },
    { name: "Tucker", primaryGyms: [], email: "Nolan.Black@movementgyms.com" },
];