export const ALL_SETTERS: { name: string; primaryGyms: string[]; email: string }[] = [
    { name: "Evan", primaryGyms: ["denton", "design"], email: "Evan@movementgyms.com" },
    { name: "Canon", primaryGyms: ["hill", "plano"], email: "Canon@movementgyms.com" },
    { name: "Austin", primaryGyms: ["fortWorth", "grapevine"], email: "Austin@movementgyms.com" },
    { name: "Luke S.", primaryGyms: ["design"], email: "LukeS@movementgyms.com" },
    { name: "Nicole", primaryGyms: ["grapevine"], email: "Nicole@movementgyms.com" },
    { name: "Jack S.", primaryGyms: ["hill", "plano"], email: "JackS@movementgyms.com" },
    { name: "Kyle", primaryGyms: ["design"], email: "Kyle@movementgyms.com" },
    { name: "Fredrik", primaryGyms: ["design"], email: "Fredrik@movementgyms.com" },
    { name: "Brandon", primaryGyms: ["hill", "plano"], email: "Brandon@movementgyms.com" },
     { name: "Theo", primaryGyms: ["hill", "plano", "carrolltonTC", "planoTC"], email: "Theo@movementgyms.com" },
    { name: "Joe", primaryGyms: ["hill", "plano"], email: "Joe@movementgyms.com" },
    { name: "Samantha", primaryGyms: ["design", "hill"], email: "Samantha@movementgyms.com" },
    { name: "Adam K.", primaryGyms: ["denton", "grapevine"], email: "AdamK@movementgyms.com" },
    { name: "Luigi", primaryGyms: ["denton", "grapevine"], email: "Luigi@movementgyms.com" },
    { name: "Mikey", primaryGyms: ["denton", "plano"], email: "Mikey@movementgyms.com" },
     { name: "Willard", primaryGyms: ["fortWorth", "grapevine"], email: "Willard@movementgyms.com" },
     { name: "Jack V.", primaryGyms: ["fortWorth", "grapevine"], email: "JackV@movementgyms.com" },
     { name: "Henry", primaryGyms: ["carrolltonTC", "planoTC"], email: "Henry@movementgyms.com" },
     { name: "Matt", primaryGyms: ["carrolltonTC", "planoTC"], email: "Matt@movementgyms.com" },
     { name: "Ellis", primaryGyms: ["carrolltonTC", "planoTC"], email: "Ellis@movementgyms.com" },
    { name: "Tucker", primaryGyms: [], email: "Tucker@movementgyms.com" },
];